### ISSUE TITLE
Dashboard page

### ISSUE THREAD

**Issue by TekMath** [G-Epitech/AFMY-Seminar#46]
Create a stat page on / to allow managers to see all stats of the company.<br>Some components: [https://ui.shadcn.com/charts](https://ui.shadcn.com/charts)

**Comment by Yann-Masson** [comment]
2 questions for our client on the Dashboard page. First, which charts the client want ? Second, if she want the first chart (cf screenshot), what is the dotted line under the main line ? (Maybe the last month ?)

<img src="https://uploads.linear.app/8f8bd164-b680-41c9-b425-5f9681adbfb1/34629753-5823-4bee-bdfc-0feb5d9ce903/8765e3c5-4fee-4ac9-9969-9179900c3579?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzhmOGJkMTY0LWI2ODAtNDFjOS1iNDI1LTVmOTY4MWFkYmZiMS8zNDYyOTc1My01ODIzLTRiZWUtYmRmYy0wZmViNWQ5Y2U5MDMvODc2NWUzYzUtNGZlZS00YWM5LTk5NjktOTE3OTkwMGMzNTc5IiwiaWF0IjoxNzI1NDgwOTk2LCJleHAiOjMzMjk2MDQwOTk2fQ.4Oq9yBus0YGsq3nAobGeHvA1EXDxWqslrYP1uswZv4k " alt="image.png" width="878" height="394" />
